### ISSUE TITLE
Could you please share a BibTex of your paper for citation?

### ISSUE THREAD

**Issue by CodingCatMountain** [RoboticsPolyu/IPN_MPC#2]
Dear  Peiwen @RoboticsPolyu :

I am writing to ask if you have published this work? and I want to ask if you would be willing to share this work's BibTex with me.

I understand that you may be busy, so I appreciate your consideration of my request.

Thank you for your time.

Sincerely,
Kacun.

**Comment by RoboticsPolyu** [comment]
Dear @CodingCatMountain , thank you very much. [ ](https://doi.org/10.48550/arXiv.2310.02542)

**Comment by RoboticsPolyu** [comment]
Dear @CodingCatMountain 
https://doi.org/10.48550/arXiv.2310.02542.
Thank you very much!
